name: Upload website to S3 bucket

# Trigger workflow every push to branch 'main'
on:
  push:
    branches:
      - main

# Necessary permissions for workflow
permissions:
  id-token: write
  contents: read
env:
  aws-region: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

        # Install awscli
      - uses: unfor19/install-aws-cli-action@v1

      # Assume the OIDC role to get temporary credentials
      - name: config aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: 'us-east-1'
          role-session-name: GitHubAction-AssumeRoleWithAction
        
      - name: Sync website to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      